version: "3.6"
services:
  stablex:
    command: ./stablex
    build:
      context: .
      dockerfile: docker/rust/Dockerfile
      args:
        - RUST_BASE=rust-binary
    image: stablex-binary-public
    environment:
      - SOLVER_TYPE=open-solver
      - RUST_BACKTRACE=1
