[package]
name = "e2e"
version = "1.0.0"
edition = "2018"

[dependencies]
ethcontract = { git = "https://github.com/gnosis/ethcontract-rs", branch = "graph-patches-v0.3.0" }
futures = { version = "0.3.4", features = ["compat"] }
driver = { path = "../driver" }